/// @desc
saved = 1;
//DONT TURN TO 0 IT WILL FUCK SAVE FILE, THIS IS SET TO 1 SO
//WHEN YOU COMPLETE A LEVEL IT SETS TO 0 SO IT WILL ACTUALLY SAVE VALUES
//WHEN oTimeController DOESNT EXSIST IT MAKES SAVEDGAME.SAVE EMPTY
//SAVE FILES ARE FOUND IN appdata/local/pleasework <-- game name directory
setSaved = 1;
firstSave = 1;